version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
  build:
    commands:
artifacts:
  files:
    - "handler/**/*"
  name: handler-$CODEBUILD_RESOLVED_SOURCE_VERSION
